
(function () {
var scripts = [{"deps":{"./assets/Script/Game2Object/TransGround":1,"./assets/Script/UImanager":2,"./assets/Script/Game1Object/ChangingGround":3,"./assets/Script/Game4Object/PlayerCoin":4,"./assets/Script/Game5Object/fight_forum":5,"./assets/Script/GameManager/GameManagerS3":6,"./assets/Script/GameEnd/GameEndManager":7,"./assets/Script/computer":8,"./assets/Script/Player":9,"./assets/Script/computerRule":10,"./assets/Script/LobbyManager":11,"./assets/Script/ready_to_S1":12,"./assets/Script/CameraManager":13,"./assets/Script/log":14,"./assets/Script/switching_from_waiting":15,"./assets/Script/Game2Object/PlayerGhost":16,"./assets/Script/Game4Object/coinManager":17,"./assets/Script/Game4Object/GameManagerCoin":18,"./assets/Script/Game5Object/battle_field":19,"./assets/Script/Game5Object/TranGround_special":20,"./assets/Script/Game5Object/fight_pressed":21,"./assets/Script/Game5Object/opponent_betting_update":22,"./assets/Script/InteractWall":23,"./assets/Script/Game5Object/utility":24,"./assets/Script/Game5Object/Mine_info_choice":25,"./assets/Script/Game5Object/special_player":26,"./assets/Script/Game5Object/panel_info":27,"./assets/Script/GameManager/GameManagerS5":28,"./assets/Script/GameManager/GameManagerS4":29,"./assets/Script/GameManager/GameManagerS2":30,"./assets/Script/GameManager/GameManagerS1":31},"path":"preview-scripts/__qc_index__.js"},{"deps":{"./PlayerGhost":16},"path":"preview-scripts/assets/Script/Game2Object/TransGround.js"},{"deps":{},"path":"preview-scripts/assets/Script/UImanager.js"},{"deps":{"../GameManager/GameManagerS1":31},"path":"preview-scripts/assets/Script/Game1Object/ChangingGround.js"},{"deps":{"../CameraManager":13,"./GameManagerCoin":18},"path":"preview-scripts/assets/Script/Game4Object/PlayerCoin.js"},{"deps":{"./battle_field":19,"../GameManager/GameManagerS5":28},"path":"preview-scripts/assets/Script/Game5Object/fight_forum.js"},{"deps":{},"path":"preview-scripts/assets/Script/GameManager/GameManagerS3.js"},{"deps":{"../Player":9},"path":"preview-scripts/assets/Script/GameEnd/GameEndManager.js"},{"deps":{"./Player":9},"path":"preview-scripts/assets/Script/computer.js"},{"deps":{"./CameraManager":13},"path":"preview-scripts/assets/Script/Player.js"},{"deps":{"./Player":9},"path":"preview-scripts/assets/Script/computerRule.js"},{"deps":{"./Player":9},"path":"preview-scripts/assets/Script/LobbyManager.js"},{"deps":{},"path":"preview-scripts/assets/Script/ready_to_S1.js"},{"deps":{},"path":"preview-scripts/assets/Script/CameraManager.js"},{"deps":{},"path":"preview-scripts/assets/Script/log.js"},{"deps":{},"path":"preview-scripts/assets/Script/switching_from_waiting.js"},{"deps":{"../CameraManager":13},"path":"preview-scripts/assets/Script/Game2Object/PlayerGhost.js"},{"deps":{"./GameManagerCoin":18},"path":"preview-scripts/assets/Script/Game4Object/coinManager.js"},{"deps":{"./PlayerCoin":4},"path":"preview-scripts/assets/Script/Game4Object/GameManagerCoin.js"},{"deps":{"../GameManager/GameManagerS5":28,"./panel_info":27},"path":"preview-scripts/assets/Script/Game5Object/battle_field.js"},{"deps":{"../Game5Object/special_player":26},"path":"preview-scripts/assets/Script/Game5Object/TranGround_special.js"},{"deps":{"../GameManager/GameManagerS5":28,"./fight_forum":5},"path":"preview-scripts/assets/Script/Game5Object/fight_pressed.js"},{"deps":{"../GameManager/GameManagerS5":28},"path":"preview-scripts/assets/Script/Game5Object/opponent_betting_update.js"},{"deps":{},"path":"preview-scripts/assets/Script/InteractWall.js"},{"deps":{"../GameManager/GameManagerS5":28},"path":"preview-scripts/assets/Script/Game5Object/utility.js"},{"deps":{"./panel_info":27,"./battle_field":19},"path":"preview-scripts/assets/Script/Game5Object/Mine_info_choice.js"},{"deps":{"../CameraManager":13,"../GameManager/GameManagerS5":28,"../UImanager":2,"../Game5Object/Mine_info_choice":25,"../Game5Object/fight_forum":5,"../Game5Object/battle_field":19},"path":"preview-scripts/assets/Script/Game5Object/special_player.js"},{"deps":{"../GameManager/GameManagerS5":28},"path":"preview-scripts/assets/Script/Game5Object/panel_info.js"},{"deps":{"../Game5Object/special_player":26,"../Game5Object/battle_field":19,"../Game5Object/Mine_info_choice":25},"path":"preview-scripts/assets/Script/GameManager/GameManagerS5.js"},{"deps":{"../Player":9},"path":"preview-scripts/assets/Script/GameManager/GameManagerS4.js"},{"deps":{"../Game2Object/PlayerGhost":16},"path":"preview-scripts/assets/Script/GameManager/GameManagerS2.js"},{"deps":{"../Player":9,"../Game1Object/ChangingGround":3},"path":"preview-scripts/assets/Script/GameManager/GameManagerS1.js"}];
var entries = ["preview-scripts/__qc_index__.js"];
var bundleScript = 'preview-scripts/__qc_bundle__.js';

/**
 * Notice: This file can not use ES6 (for IE 11)
 */
var modules = {};
var name2path = {};

// Will generated by module.js plugin
// var scripts = ${scripts};
// var entries = ${entries};
// var bundleScript = ${bundleScript};

if (typeof global === 'undefined') {
    window.global = window;
}

var isJSB = typeof jsb !== 'undefined';

function getXMLHttpRequest () {
    return window.XMLHttpRequest ? new window.XMLHttpRequest() : new ActiveXObject('MSXML2.XMLHTTP');
}

function downloadText(url, callback) {
    if (isJSB) {
        var result = jsb.fileUtils.getStringFromFile(url);
        callback(null, result);
        return;
    }

    var xhr = getXMLHttpRequest(),
        errInfo = 'Load text file failed: ' + url;
    xhr.open('GET', url, true);
    if (xhr.overrideMimeType) xhr.overrideMimeType('text\/plain; charset=utf-8');
    xhr.onload = function () {
        if (xhr.readyState === 4) {
            if (xhr.status === 200 || xhr.status === 0) {
                callback(null, xhr.responseText);
            }
            else {
                callback({status:xhr.status, errorMessage:errInfo + ', status: ' + xhr.status});
            }
        }
        else {
            callback({status:xhr.status, errorMessage:errInfo + '(wrong readyState)'});
        }
    };
    xhr.onerror = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(error)'});
    };
    xhr.ontimeout = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(time out)'});
    };
    xhr.send(null);
};

function loadScript (src, cb) {
    if (typeof require !== 'undefined') {
        require(src);
        return cb();
    }

    // var timer = 'load ' + src;
    // console.time(timer);

    var scriptElement = document.createElement('script');

    function done() {
        // console.timeEnd(timer);
        // deallocation immediate whatever
        scriptElement.remove();
    }

    scriptElement.onload = function () {
        done();
        cb();
    };
    scriptElement.onerror = function () {
        done();
        var error = 'Failed to load ' + src;
        console.error(error);
        cb(new Error(error));
    };
    scriptElement.setAttribute('type','text/javascript');
    scriptElement.setAttribute('charset', 'utf-8');
    scriptElement.setAttribute('src', src);

    document.head.appendChild(scriptElement);
}

function loadScripts (srcs, cb) {
    var n = srcs.length;

    srcs.forEach(function (src) {
        loadScript(src, function () {
            n--;
            if (n === 0) {
                cb();
            }
        });
    })
}

function formatPath (path) {
    let destPath = window.__quick_compile_project__.destPath;
    if (destPath) {
        let prefix = 'preview-scripts';
        if (destPath[destPath.length - 1] === '/') {
            prefix += '/';
        }
        path = path.replace(prefix, destPath);
    }
    return path;
}

window.__quick_compile_project__ = {
    destPath: '',

    registerModule: function (path, module) {
        path = formatPath(path);
        modules[path].module = module;
    },

    registerModuleFunc: function (path, func) {
        path = formatPath(path);
        modules[path].func = func;

        var sections = path.split('/');
        var name = sections[sections.length - 1];
        name = name.replace(/\.(?:js|ts|json)$/i, '');
        name2path[name] = path;
    },

    require: function (request, path) {
        var m, requestScript;

        path = formatPath(path);
        if (path) {
            m = modules[path];
            if (!m) {
                console.warn('Can not find module for path : ' + path);
                return null;
            }
        }

        if (m) {
            let depIndex = m.deps[request];
            // dependence script was excluded
            if (depIndex === -1) {
                return null;
            }
            else {
                requestScript = scripts[ m.deps[request] ];
            }
        }
        
        let requestPath = '';
        if (!requestScript) {
            // search from name2path when request is a dynamic module name
            if (/^[\w- .]*$/.test(request)) {
                requestPath = name2path[request];
            }

            if (!requestPath) {
                if (CC_JSB) {
                    return require(request);
                }
                else {
                    console.warn('Can not find deps [' + request + '] for path : ' + path);
                    return null;
                }
            }
        }
        else {
            requestPath = formatPath(requestScript.path);
        }

        let requestModule = modules[requestPath];
        if (!requestModule) {
            console.warn('Can not find request module for path : ' + requestPath);
            return null;
        }

        if (!requestModule.module && requestModule.func) {
            requestModule.func();
        }

        if (!requestModule.module) {
            console.warn('Can not find requestModule.module for path : ' + path);
            return null;
        }

        return requestModule.module.exports;
    },

    run: function () {
        entries.forEach(function (entry) {
            entry = formatPath(entry);
            var module = modules[entry];
            if (!module.module) {
                module.func();
            }
        });
    },

    load: function (cb) {
        var self = this;

        var srcs = scripts.map(function (script) {
            var path = formatPath(script.path);
            modules[path] = script;

            if (script.mtime) {
                path += ("?mtime=" + script.mtime);
            }
            return path;
        });

        console.time && console.time('load __quick_compile_project__');
        // jsb can not analysis sourcemap, so keep separate files.
        if (bundleScript && !isJSB) {
            downloadText(formatPath(bundleScript), function (err, bundleSource) {
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                if (err) {
                    console.error(err);
                    return;
                }

                let evalTime = 'eval __quick_compile_project__ : ' + srcs.length + ' files';
                console.time && console.time(evalTime);
                var sources = bundleSource.split('\n//------QC-SOURCE-SPLIT------\n');
                for (var i = 0; i < sources.length; i++) {
                    if (sources[i]) {
                        window.eval(sources[i]);
                        // not sure why new Function cannot set breakpoints precisely
                        // new Function(sources[i])()
                    }
                }
                self.run();
                console.timeEnd && console.timeEnd(evalTime);
                cb();
            })
        }
        else {
            loadScripts(srcs, function () {
                self.run();
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                cb();
            });
        }
    }
};

// Polyfill for IE 11
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function () {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
})();
    